### ISSUE TITLE
End date not highlighted when it is the first cell on a calendar's grid

### ISSUE THREAD

**Issue by neverfox** [onefinestay/react-daterange-picker#102]
To recreate:
- Open demo page and go to the first example (where Sunday is the first day of the week, which is key to recreating the bug)
- Page through the calendars so that Oct 2015 is the first calendar
- Pick any date in Oct as the start date
- Drag the range until you are hovering over Nov 1 (should be the first day on the second calendar's grid)

The date doesn't get any highlighting. If you click it as the end date, it correctly recognizes it but the CSS is never applied. Same thing happens under similar circumstances. See, for example, Jan-Feb 2016 on the first calendar on the demo page (where Mon is the start of the week).

**Comment by AlanFoster** [comment]
This is fixed in the latest version now :+1:
