### ISSUE TITLE
Selecting a single day

### ISSUE THREAD

**Issue by jerefrer** [onefinestay/react-daterange-picker#110]
Could it be possible to select a single day ?
Perhaps by clicking on a day, and then clicking on the same day to end the selection ?

What do you think ?

Anyway, thanks for this awesome picker !

**Comment by AlanFoster** [comment]
@jerefrer We already support this functionality with the `singleDateRange ` prop ([source](https://github.com/onefinestay/react-daterange-picker/blob/59a29acc9095cb647a2609ead120974867fc6fe6/example/index.jsx#L181)).
Check out our examples page too - http://onefinestay.github.io/react-daterange-picker/

Let me know if you have any other issues :+1:

**Comment by jerefrer** [comment]
Oh sorry I missed  that ... it's even more awesome than I thought :+1:
