### ISSUE TITLE
Show/Hide Calendar

### ISSUE THREAD

**Issue by harrybabu** [onefinestay/react-daterange-picker#112]
Is there an inbuilt method for Show/Hide calendar?

**Comment by AlanFoster** [comment]
@harrybabu Hi sorry for the belated response; What is your use case? Could you say specifically what parts you want to hide / show?

**Comment by RusAlex** [comment]
Suppose he @harrybabu meant to show hide picker completely. I also met this, as usually other datepickers has built-in show/hide picker functional. 

Does authors think it's not component responsibility ?

**Comment by ashachakrapani** [comment]
Is there a way to show/hide the component i.e the calendar as a whole?

**Comment by ashachakrapani** [comment]
Is there a way/prop to show/hide the component i.e the calendar as a whole?

**Comment by AlanFoster** [comment]
@ashachakrapani Is this functionality needed within this component library directly, or can you implement it within your own React application?

**Comment by AlanFoster** [comment]
I've thrown together a quick code code sandbox demonstrating this functionality:

![example](https://user-images.githubusercontent.com/1271782/40519757-40330a5c-5fb9-11e8-98c9-07a7b68aedf3.gif)

The sandbox code can be found here - https://codesandbox.io/s/0xv5m04yql

Let me know if there's any issues :+1:

**Comment by AlanFoster** [comment]
Closing this off, let me know if you're still having difficulties and we can reopen this if need be :+1:
