### ISSUE TITLE
Add shouldComponentUpdate to reduce the wasted time

### ISSUE THREAD

**Issue by joseph1125** [onefinestay/react-daterange-picker#139]
I was working on a page written in React, when I use React Perf to monitor performance, I found that this component wastes quite a lot of time. I recommend adding shouldComponentUpdate to reduce the wasted time and make the re-render much faster.

![image](https://cloud.githubusercontent.com/assets/8279406/15492085/07c01e84-21aa-11e6-84fd-71651ce1b5bf.png)

**Comment by AlanFoster** [comment]
@joseph1125 Thanks for the heads-up. Mind putting up a quick PR for this? :+1:
