### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by maullerz** [onefinestay/react-daterange-picker#140]
To be or not to be?
Big thanks and appreciate for this nice and beautiful component.
But what about future and supporting?
May be it is time to fork and continue to work on this in another repo?
Probably someone already started, any links?

**Comment by AlanFoster** [comment]
@maullerz Yes - sorry, the project is definitely still alive.

I need to allocate some time into reviewing and merging the final PRs :+1:
