### ISSUE TITLE
React 

### ISSUE THREAD

**Issue by manulourdes** [onefinestay/react-daterange-picker#145]
Hello i am new to react and i am testing it on a project but whne i do the npm install i get this
```

Leals-MacBook-Air:snapchat Manu$ npm install
SnapChat@0.0.1 /Users/Manu/Desktop/SnapChat
└── react@15.0.2 
npm WARN react-addons-pure-render-mixin@15.2.0 requires a peer of react@^15.2.0 but none was installed.
```

when i do the npm update 
```
Leals-MacBook-Air:snapchat Manu$ npm update
SnapChat@0.0.1 /Users/Manu/Desktop/SnapChat
└── react-native-camera@0.3.8  (git+https://github.com/lwansbrough/react-native-camera.git#d4d1aec581e085e9152e124b69b6aecb117b7378)

npm WARN react-addons-pure-render-mixin@15.2.0 requires a peer of react@^15.2.0 but none was installed.
```

i don't know what to do now about the react 15.2.0 on the package.json

the react is 15.0.2 so i don't know what to do

**Comment by michaeljonsampson** [comment]
This PR should fix that https://github.com/onefinestay/react-daterange-picker/pull/135
It has already been merged. We are waiting on the maintainers to make another release. 
Any time frame on that? I'm waiting for it too.

**Comment by AlanFoster** [comment]
@manulourdes @michaeljonsampson Version 1.1.0 of `react-daterange-picker` has now been released. Let me know if there are any issues :+1:

**Comment by AlanFoster** [comment]
Closing for now; let me know if there's any further issues
