### ISSUE TITLE
selectionType both single and range possible?

### ISSUE THREAD

**Issue by msathis** [onefinestay/react-daterange-picker#152]
Is selecting either single date or range is possible? Now the option allows either one of them.

**Comment by maullerz** [comment]
@msathis yes, you need this prop: [singleDateRange](https://github.com/onefinestay/react-daterange-picker/blob/master/src/DateRangePicker.jsx#L53)

**Comment by msathis** [comment]
Thanks.. My bad.. missed it somehow :(
