### ISSUE TITLE
New release 1.2.0

### ISSUE THREAD

**Issue by onedesert** [onefinestay/react-daterange-picker#158]
Hey,

I would like to know when you plan to push new version as I need some fix that this new version has. I've published a copy of the package in the meanwhile as we need this fix for production.

Thanks!

BTW great component !!

**Comment by AlanFoster** [comment]
The latest code has now been published as [1.12.0](https://github.com/onefinestay/react-daterange-picker/releases/tag/v1.2.0) and is available on npm.

Please let me know if there are any issues with the new release, or release notes. I will to keep an eye on pull requests to help get them merged and released as soon as possible :+1:

Thanks everyone that helped contribute to this release 🎉
