### ISSUE TITLE
Object assign is undefined

### ISSUE THREAD

**Issue by darshan-raj** [onefinestay/react-daterange-picker#16]
I am getting an error ``Object.assign is undefined`` from BemMixin.js. I am using it in my code by doing an npm install and then bundling it using webpack. Am I missing something here? My chrome version is ``Version 41.0.2272.89 (64-bit)``

![screen shot 2015-03-21 at 7 40 59 pm](https://cloud.githubusercontent.com/assets/1267110/6765367/e5178fec-d002-11e4-8a00-84cca929b26f.png)

**Comment by jkimbo** [comment]
`Object.assign` is a new es6 feature (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) and so you need a polyfill to use it in current browsers. We currently use https://cdn.polyfill.io/v1/docs/

I'm going to leave this ticket open to track adding this to the requirements in the readme.
