### ISSUE TITLE
When will 1.2 be released?

### ISSUE THREAD

**Issue by rdejuana** [onefinestay/react-daterange-picker#170]

**Comment by moimikey** [comment]
i may take the liberty of releasing it myself since the project is not maintained as heavily as it previously was.

**Comment by Maxoos** [comment]
Can you please do @moimikey, I'm having issues and I think this new version might help.

**Comment by rdejuana** [comment]
my coworker put a fork of master up yesterday at https://www.npmjs.com/package/@octalmage/react-daterange-picker

Feel free to use this, but realize we are not maintaining it, it's there just as a stop gap until the real 1.2 comes out.

FYI, the feature/bug fix we needed was focus month and year when state change occurs externally

**Comment by moimikey** [comment]
;x i don't have npm access. @AlanFoster

**Comment by moimikey** [comment]
hi @AlanFoster :)

**Comment by AlanFoster** [comment]
The latest code has now been published as [1.12.0](https://github.com/onefinestay/react-daterange-picker/releases/tag/v1.2.0) and is available on npm.

Please let me know if there are any issues with the new release, or release notes. I will to keep an eye on pull requests to help get them merged and released as soon as possible :+1:

Thanks everyone that helped contribute to this release 🎉

**Comment by AlanFoster** [comment]
hi @moimikey ! :)
