### ISSUE TITLE
Is someone still maintaining this repository?

### ISSUE THREAD

**Issue by jontelm** [onefinestay/react-daterange-picker#172]
Is someone still maintaining this repository?

I have done some PR:s but got no response so I don't create any PR:s anymore.

**Comment by wmertens** [comment]
@AlanFoster only comes by every half- to full year, unfortunately.

**Comment by wmertens** [comment]
Anybody up for maintaining a fork? Much respect to @AlanFoster but it seems he can't afford the time 😞

**Comment by AlanFoster** [comment]
The latest code has now been published as [1.12.0](https://github.com/onefinestay/react-daterange-picker/releases/tag/v1.2.0) and is available on npm.

Please let me know if there are any issues with the new release, or release notes. I will to keep an eye on pull requests to help get them merged and released as soon as possible :+1:

Thanks everyone that helped contribute to this release 🎉
