### ISSUE TITLE
Are there plans to publish a new version ?

### ISSUE THREAD

**Issue by gillchristian** [onefinestay/react-daterange-picker#181]
Hi! I see the project does not look to be active ( #172 ). Are there plans to publish a new version ? 

I see there are improvements [already commited](https://github.com/onefinestay/react-daterange-picker/blob/master/src/calendar/CalendarMonth.jsx#L30-L34) to the way locale is [handled now in `1.1.0`](https://github.com/onefinestay/react-daterange-picker/blob/24d357c20e3adc20e95363682b0f7d54274d228d/src/calendar/CalendarMonth.jsx#L12-L15). Right now I'm not able to fully localize the date picker and having those changes published will be much appreciated.

Also with React v16 coming soon there are several updates needed (`prop-types`, `React.createClass`).

**Comment by dsteinbach** [comment]
Wish i saw this issue sooner :(

**Comment by jeznag** [comment]
https://github.com/Yaska/react-daterange-picker/pull/1 seems to have some momentum @chiss2906 any updates?

**Comment by AlanFoster** [comment]
The latest code has now been published as [1.12.0](https://github.com/onefinestay/react-daterange-picker/releases/tag/v1.2.0) and is available on npm.

Please let me know if there are any issues with the new release, or release notes. I will to keep an eye on pull requests to help get them merged and released as soon as possible :+1:

Thanks everyone that helped contribute to this release 🎉
