### ISSUE TITLE
demo is broken

### ISSUE THREAD

**Issue by luisrudge** [onefinestay/react-daterange-picker#27]
Uncaught Error: Invariant Violation: You're trying to render a component to the document using server rendering but the checksum was invalid. This usually means you rendered a different component type or props on the client from the one on the server, or your render() methods are impure. React cannot handle this case due to cross-browser quirks by rendering at the document root. You should look for environment dependent code in your components and ensure the props are the same client and server side.

**Comment by jkimbo** [comment]
@luisrudge it seems to be working for me? What browser are you using? Also have you tried doing a hard reload? We don't do any cache busting on the assets so if you've viewed the page before you might be loading in cached files.

**Comment by luisrudge** [comment]
@jkimbo I'm on chrome. It fails even with the incognito mode (without extensions)
