### ISSUE TITLE
show calendar on focus

### ISSUE THREAD

**Issue by luisrudge** [onefinestay/react-daterange-picker#30]
it's possible? :)

**Comment by jkimbo** [comment]
I don't quite understand what you mean by this? The calendar is not tied to anything else so it is up to you how and when you want to show it. For example on http://onefinestay.com/ we show the calendar in a popover when you click on one of the date fields.

Does that help?

**Comment by luisrudge** [comment]
Ahhh yeah. That does makes sense. I keep forgetting that it is just javascript :)
Thanks!

**Comment by 98rahul** [comment]
@jkimbo  man! In your **http://onefinestay.com/** have used Date-Range-Picker,I would like to know how calendar getting closed  on outside Click.
Please Share  piece of code!
