### ISSUE TITLE
Can't select dates with windows phone

### ISSUE THREAD

**Issue by luisrudge** [onefinestay/react-daterange-picker#31]
![wp](https://cloud.githubusercontent.com/assets/941075/7524809/f378bf8c-f4da-11e4-8d9c-ed285afe2db8.gif)

**Comment by luisrudge** [comment]
Sorry about my mouse cursor in the middle of the screen :)

**Comment by luisrudge** [comment]
Sorry, this is with the demo, which isn't up to date with master. Can you publish again? Thanks

**Comment by luisrudge** [comment]
Ok, using the latest version I can select the dates, but it's pretty slow. :(

**Comment by jkimbo** [comment]
@luisrudge yep we are aware it is slow at the moment and we are looking into improving the performance. One of the reasons its slow on the demo site is that we are running an unoptimised versions of React and so it is doing a lot of unnecessary checks on PropTypes etc. In production we minify all our code so it does perform better.
