### ISSUE TITLE
Warning: owner-based and parent-based contexts differ

### ISSUE THREAD

**Issue by jimmyn** [onefinestay/react-daterange-picker#40]
I'm trying to set up DatePicker but I'm getting tons of warnings in console
```
Warning: owner-based and parent-based contexts differ (values: `undefined` vs `DateRangePicker`) for key (bemBlock) while mounting PaginationArrow
```
```
Warning: owner-based and parent-based contexts differ (values: `undefined` vs `null`) for key (bemNamespace) while mounting PaginationArrow
```
I figured out that problem is in BemMixin
Somehow context wasn't transferred to child components

**Comment by jimmyn** [comment]
Looks like it happens only when I use browserify. Example with webpack works perfect

**Comment by jkimbo** [comment]
@jimmyn weird, I'll have a look into it as soon as I can.

**Comment by jimmyn** [comment]
@jkimbo sorry, I figured out that it is because React was declared globally 
```global.React = require 'react/addons'```

**Comment by neverfox** [comment]
I'm getting the same thing trying to render this in the react-redux-start-kit, but React is not declared globally there as far as I can tell.

**Comment by jkimbo** [comment]
@neverfox if you can provide an example of the bug that would be very helpful

**Comment by carlesandres** [comment]
I'm facing the same issue, but I need to keep using React as a global variable. 

Is there any way I can workaround this issue?

I'm using react-daterange-picker@0.12.0 and react@0.13.3.
