### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by jimmyn** [onefinestay/react-daterange-picker#41]
I'm getting uncaught error in moment-range.js in demo or when I'm trying to use module
```Uncaught TypeError: Cannot read property 'length' of undefined```

Apparently moment-range higher than 1.0.9 causes this error

**Comment by jkimbo** [comment]
@jimmyn do you have a stack trace or example code that triggers the error?

**Comment by jimmyn** [comment]
If you update moment-range up to 1.1.0 it will trigger the error in example.
Apparently moment-range doesn't work as a moment object when you don't pass any arguments any more. And ```const lang = moment().localeData()``` causes error

This is the stuck trace. 
```
DateRange (moment-range.js?a4bb:47)
(anonymous function) (CalendarMonth.js?0bc9:59)
(anonymous function) (index.js:1187)
__webpack_require__ (index.js:20)
(anonymous function) (DateRangePicker.js?6f5d:38)
(anonymous function) (index.js:1133)
__webpack_require__ (index.js:20)
(anonymous function) (index.js?4a85:11)
(anonymous function) (index.js:1127)
__webpack_require__ (index.js:20)
(anonymous function) (index.jsx?073c:9)
(anonymous function) (index.js:1091)
__webpack_require__ (index.js:20)
(anonymous function) (index.js?e382:4)
(anonymous function) (index.js:47)
__webpack_require__ (index.js:20)
(anonymous function) (index.js:40)
(anonymous function) (index.js:43)
```

Here is the code that causes this error
```
function DateRange(start, end) {
  var parts;
  var s = start;
  var e = end;

  if (arguments.length === 1 || end === undefined) {
    if (start.length === 2) { // Infer array
      s = start[0];
      e = start[1];
    }
    else {
      parts = start.split('/');
      s = parts[0];
      e = parts[1];
    }
  }

  this.start = moment(s);
  this.end   = moment(e);
}
```

**Comment by AndrewIngram** [comment]
Trying to work out the most suitable fix for this. Obviously we can pin the version of moment-range, but then if you're using it anywhere else, there'll be issues in terms of bundle sizes or compatibility. Maybe we can put in a little compatibility shim in the short term.
