### ISSUE TITLE
Change locale

### ISSUE THREAD

**Issue by miracle2k** [onefinestay/react-daterange-picker#44]
I am trying to change the locale, but I can't figure it out.

In my own code:

```
var moment = require('moment');
require('moment/locale/de');
moment.locale('de');
```

works just fine for my own moment() code. However, this never affects the datepicker.

When I go into a debugger in `CalenderMonth.js`, `moment.locale()` always returns "en". Changing it to "de" right there has no effect either; I am wondering if there is some confusion about "moment" and "moment-range", and that my "de" locale is never available in the right place.

Any ideas?

**Comment by AndrewIngram** [comment]
It would make sense to me to be able to pass in locale as a prop

**Comment by miracle2k** [comment]
I'm not sure if that is possible; isn't the moment locale global, at least in theory?

**Comment by AndrewIngram** [comment]
That's what i'd been depending on :cry: 

I'd prefer to ditch moment-range anyway, I don't like libraries that attach themselves to other libraries.

**Comment by dmitry** [comment]
> It would make sense to me to be able to pass in locale as a prop

I agree with that. In other case if you have, for example 10 locales, you have to load them all. Not nice. Also in our case we are using `i18n-js` library, and for us it's much more easier to translate json locale files in one place.

**Comment by dmitry** [comment]
I like how it's done for this library: http://www.gpbl.org/react-day-picker/
Look for the prop name `localeUtils`. What if the same will be implemented for this component?

**Comment by miracle2k** [comment]
Ok so I look at this more. The first issue was with my transform stack. ES6 imports, which I used, always go to the top of the file, so there is no way to make my call to ``moment.locale()`` go before the DateRangePicker import.

Even that though doesn't fix it, because for some reason, when ``DateRangePicker`` loads ``moment-range``, the module init code (?) of ``moment`` is run again, and resets the locale to "en". Why that is I don't understand. Maybe an issue with browserify?

Anyway, one option might be to simply delay pulling the strings from moment until the component is loaded.

**Comment by dmitry** [comment]
To prevent loading locale files at all, I've used webpack `noParse: [/moment\.js/]` rule. But it doesn't solve all the translation problems. :(

**Comment by thaerlabs** [comment]
Hey guys, please if you can test this pull request and provide your feedback it would be great..
https://github.com/onefinestay/react-daterange-picker/pull/119

**Comment by AlanFoster** [comment]
Closing this ticket off, as react-daterange-picker supports locale functionality now :+1:
