### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by miracle2k** [onefinestay/react-daterange-picker#49]
This is what I get on "gulp build-example-js":

    ERROR in ./example/js/index.js
    Module build failed: SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
    at Parser.pp.raise

**Comment by AlanFoster** [comment]
@miracle2k Not reproducible for me unfortunately. Is this still an issue for yourself? :)

```
> gulp build-example-js 
[11:53:59] Using gulpfile ~/Documents/Shopkeep/js/react-daterange-picker/gulpfile.js
[11:53:59] Starting 'build-example-js'...
[11:54:03] Version: webpack 1.10.5
   Asset     Size  Chunks             Chunk Names
index.js  2.75 MB       0  [emitted]  main
[11:54:03] Finished 'build-example-js' after 3.23 s
```

**Comment by miracle2k** [comment]
With a fresh checkout, I don't have the problem anymore. Strange.
