### ISSUE TITLE
Include CSS as part of the NPM package

### ISSUE THREAD

**Issue by stevewillard** [onefinestay/react-daterange-picker#68]
Is there any chance you could include the CSS from the demo page (http://onefinestay.github.io/react-daterange-picker/) as part of what's published on NPM?

(In reference to the CSS in the demo page)

**Comment by noygal** [comment]
+1

**Comment by nicoecheza** [comment]
+1

**Comment by rolyatmax** [comment]
+1

**Comment by AlanFoster** [comment]
@stevewillard Sounds good to me; Happy to merge a PR request for this.

**Comment by MattAttack** [comment]
+1

**Comment by AlanFoster** [comment]
This should be resolved now by #99 and available as part of the v0.12.2 release
