### ISSUE TITLE
CALL FOR MAINTAINERS

### ISSUE THREAD

**Issue by jkimbo** [onefinestay/react-daterange-picker#74]
We are no longer using this project in production at onefinestay so it's becoming hard to maintain it. Rather than just let the project decay I would like to add some more people as maintainers so that they can take the project wherever they see fit! Is anyone up for it?

cc. @moimikey @AlanFoster @HelenDea @nicolassenechal @ckald @Maxim-Filimonov @miracle2k

**Comment by ckald** [comment]
I do not use it in production yet, so I might be only a semi-active maintainer. It's up to you, I guess

**Comment by moimikey** [comment]
@AlanFoster, myself, and our team are currently using it in production. I can't speak for him, but we'd probably be very interested.

**Comment by alistairjcbrown** [comment]
:+1: @moimikey - we use it in production

**Comment by AlanFoster** [comment]
I'm happy to be added to the maintainers list, participating in Code Review etc.

**Comment by nicolassenechal** [comment]
Not using in prod at this stage. I can provide a small level of support in the next couple of months, not so sure after that :)

**Comment by jkimbo** [comment]
Thanks all, I think for the moment @AlanFoster @moimikey should be added as maintainers and if anyone else desperately wants to be involved then we can expand it. Unfortunately the person at onefinestay who can add contributors is not in today so we'll have to wait until Monday but feel free to get stuck in @AlanFoster @moimikey .

Also if we could keep raising pull requests for changes to maintain visibility that would be great! I'll try and be as active as I can.

**Comment by Maxim-Filimonov** [comment]
Not using it in product yet but might be in the future. I can offer some level of help with Code reviews

**Comment by mindjuice** [comment]
I'll be using it "in production" for an internal app that will go live in about 2-3 weeks across a team of about 500+ developers.

**Comment by jkimbo** [comment]
Closing this as @AlanFoster @moimikey have now been added as collaborators.

**Comment by moimikey** [comment]
awesome. we're looking forward.
