### ISSUE TITLE
Add a target for paging whilst dragging

### ISSUE THREAD

**Issue by AndrewIngram** [onefinestay/react-daterange-picker#8]
At the moment we have a hidden feature where dragging a selection over the next/previous arrows will trigger pagination. We need to make this more obvious, and pretty.

**Comment by AlanFoster** [comment]
We found this hidden feature to be unexpected, and sometimes difficult to use unfortunately.

I have created created the PR #53 to make this feature configurable. It would be great to get that merged in :)

**Comment by AndrewIngram** [comment]
Current thinking is to disable the functionality on mouseEnter, since the transition is too fast and unexpected. We implemented it originally so that touch-dragging would be easier on mobile, but since touchenter doesn't exist (and is annoying to implement), we can remove it for now.

Eventually the idea would be to have a timer (with visual indicator) so that the behaviour isn't triggered immediately, but rather with a short delay.

**Comment by AlanFoster** [comment]
@AndrewIngram Thanks for the visibility on that. I've put up #54 to remove this feature for now in that case.

It would be great to get either #53 or #54 merged :) Or potentially, updating #53 to have onmouseenter pagination turned off by default - so there is still a point of configuration for developers that want to use this react component.
