### ISSUE TITLE
Enable Travis

### ISSUE THREAD

**Issue by AlanFoster** [onefinestay/react-daterange-picker#83]
Once #72 is merged, we should have Travis running as our CI. This will also help provide the certainty that the React 0.14.x upgrade is working as expected too

Unfortunately I don't have Admin rights for this currently; Could we enable this please -

![image](https://cloud.githubusercontent.com/assets/1271782/10678024/a5f60fba-7907-11e5-8955-6f734b21ea4a.png)

/cc @AndrewIngram @jkimbo

**Comment by moimikey** [comment]
:+1:

**Comment by jkimbo** [comment]
@AlanFoster travis has been enabled for this project. You'll need to create a `.travis.yml` file but other than that you should be good to go!

**Comment by AlanFoster** [comment]
Delivered with #89. Closing.
