### ISSUE TITLE
Tests!

### ISSUE THREAD

**Issue by AndrewIngram** [onefinestay/react-daterange-picker#9]

**Comment by nicolassenechal** [comment]
Is there any update on testing? We are keen to use this project but the lack of unit tests is a bit of a worry for us. Happy to deal with the task to get it unblocked. Please me know if I can help!

**Comment by jkimbo** [comment]
@nicolassenechal sorry we probably won't have any time in the near future to tackle this but if you would like to help out that would be fantastic!

**Comment by nicolassenechal** [comment]
Got this underway:
https://github.com/nicolassenechal/react-daterange-picker/tree/test-setup

It is a simple karma setup. I only started working on the components. Please let me know if you are happy with this approach and I will create a merge request.
