### ISSUE TITLE
Release 0.12.2

### ISSUE THREAD

**Issue by AlanFoster** [onefinestay/react-daterange-picker#91]
Current master (e8e7f86614d8c5ff7eb7e8ac9d90f46212ba8244) reflects the work involved in a 0.12.2 release. 

The main change involved in this release is locking down our peer dependency version of react to `^0.12.0 || ^0.13.0`

/cc @AndrewIngram @jkimbo Could you please review and release as appropriate, as I do not have the permissions to do so.

**Comment by jkimbo** [comment]
@AlanFoster please do add your self to the owner list in the `package.json` which should allow you publish new releases to npm

**Comment by AlanFoster** [comment]
@jkimbo Attempting to publish 0.12.2 and I am unable to do so - 

```
> npm publish ./

...

npm ERR! You do not have permission to publish 'react-daterange-picker'. Are you logged in as the correct user? : react-daterange-picker
```

From the docs [here](https://docs.npmjs.com/cli/owner) it shows I am not a collaborator, and therefore won't have any permissions to publish a new release -

```
> npm owner ls
onefinestay <externalaccount.npmjs@onefinestay.com>
```

If I understand correctly I should be able to complete this release after this has been ran by the `onefinestay` npm owner

```
npm owner add alanfoster
```

Let me know if I've missed out on anything

**Comment by jkimbo** [comment]
@AlanFoster must have missed that in the docs, sorry about that! I've just run those commands so you should be able to publish now.

**Comment by AlanFoster** [comment]
@jkimbo Brilliant; Thanks! v0.12.2 released now :+1:
